name: Build My Apllication

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List File in Directory
        run: ls
      - name: Check Dotnet Cli
        run: dotnet build
      - name: List File in Directory
        run: ls TrickingLibrary.Api/ -R
      - name: Check NPM Cli
        run: npm -v
